### ISSUE TITLE
Adding a license to our repo ⚖️

### ISSUE THREAD

**Issue by DDCreationStudios** [FCCVienna/FCCVienna#8]

**Comment by MatthiasLiszt** [comment]
hi ... could not find the >>license file << in the repo ... i want to add the license to my repos /projects too just to be compatible

**Comment by DDCreationStudios** [comment]
@MatthiasLiszt  That's the issues section here, which means that we discuss issues/problems/bugs in this repo. In this issue number I suggested to create a license for our repo. As you pointed out correctly we don't have a license yet. If you have ideas what license fits best for our needs, don't hesitate to suggest them here. :)
Also, keep in mind that our discussion circle in the next meetup will be about licenses. Therefore the more you know about that topic the better it is :)

**Comment by 42pre** [comment]
Hi @DDCreationStudios !

As you mentioned in today's meetup's discussion on licenses https://choosealicense.com/ is a good resource for choosing an open source license. To borrow from their website:

> Mixed Projects
>If your project contains a mix of software and other material, you can include multiple licenses, as long as you are explicit about which license applies to what parts of the project. See the license notice for this site as an example.

Keeping that quote in mind and because I really like the idea behind "free software" (see [What is free software?](https://www.gnu.org/philosophy/free-sw.html)), to get the discussion rolling, I suggest using a mixed license model with a [GPL compatible free software license](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) for any code sections (eg mobprogramming), and a [free document license](https://www.gnu.org/licenses/license-list.html#FreeDocumentationLicenses) for non-program sections (talks?).

**Comment by 42pre** [comment]
These "escalating" questions might help decide on a license:

* How simply do we want it (CC0, "MIT", GPL, ...)?
* How far [copyleft](https://www.gnu.org/copyleft/copyleft.html) do we want to go? Should all derived works be required to use our chosen license or do we want to be more lenient?
* How thoroughly should contributions be vetted for any license violations or incompatibilities with the license(s) chosen by FCCVienna? (code of conduct!)

**Comment by DDCreationStudios** [comment]
pull request merged #24 .

Open for any other ideas and improvements
